// backend/src/modules/sync/mappers/cupom.mapper.ts
//
// Converte os objetos retornados pela API VarejoFácil (endpoint cupons-fiscais)
// nos formatos esperados pelas tabelas `cupom`, `cupom_item` e `cupom_finalizacao`.

/* eslint-disable @typescript-eslint/no-explicit-any */

/** Helper: converte valor para string decimal ou null */
const d = (v: unknown): string | null => (v != null ? String(v) : null);

// ─── Mapper do Cupom principal ───────────────────────────────────────────────

export function mapCupomToDb(item: any) {
  return {
    external_id:                           Number(item.identificadorId),
    id_externo:                            item.id ?? null,
    coo:                                   item.coo ?? null,
    sequencial:                            item.sequencial ?? null,
    numero_caixa:                          item.numeroCaixa ?? null,
    numero_equipamento:                    item.numeroEquipamento ?? null,
    serie_equipamento:                     item.serieEquipamento ?? null,
    sequencial_operador:                   item.sequencialOperador ?? null,
    codigo_impressora:                     item.codigoImpressora ?? null,
    contador_documento:                    item.contadorDocumento ?? null,
    chave_eletronica:                      item.chaveEletronica ?? null,
    numero_do_protocolo:                   item.numeroDoProtocolo ?? null,
    status_xml_nota:                       item.statusXMLNota ?? null,
    data:                                  item.data ? new Date(item.data) : new Date(),
    data_venda:                            item.dataVenda ? new Date(item.dataVenda) : null,
    hora:                                  item.hora ?? null,
    data_hora_abertura_cupom:              item.dataHoraAberturaCupom ?? null,
    data_hora_fechamento_cupom:            item.dataHoraFechamentoCupom ?? null,
    criado_em:                             item.criadoEm ? new Date(item.criadoEm) : null,
    nome_consumidor:                       item.nomeConsumidor ?? null,
    cpf_consumidor:                        item.cpfConsumidor ?? null,
    valor:                                 d(item.valor) ?? '0',
    acrescimo:                             d(item.acrescimo),
    desconto:                              d(item.desconto),
    valor_desconto_fidelidade:             d(item.valorDescontoFidelidade),
    valor_servico:                         d(item.valorServico),
    valor_itens_cancelados:                d(item.valorItensCancelados),
    margem_desconto:                       d(item.margemDesconto),
    qtd_itens_cupom:                       d(item.qtdItensCupom),
    qtd_itens_cancelados:                  d(item.qtdItensCancelados),
    qtd_unidades_cupom:                    d(item.qtdUnidadesCupom),
    qtd_unidades_canceladas:               d(item.qtdUnidadesCanceladas),
    cancelada:                             item.cancelada ?? null,
    imprimiu_nota_fiscal:                  item.imprimiuNotaFiscal ?? null,
    tem_itens_vendido_em_oferta:           item.temItensVendidoEmOferta ?? null,
    abono_servico:                         item.abonoServico ?? null,
    justificativa_cancelamento:            item.justificativaCancelamento ?? null,
    sequencial_cupom_cancelado:            item.sequencialCupomCancelado ?? null,
    codigo_motivo_cancelamento_id:         item.codigoMotivoCancelamentoId ? Number(item.codigoMotivoCancelamentoId) : null,
    justificativa_desconto:                item.justificativaDesconto ?? null,
    codigo_motivo_desconto_id:             item.codigoMotivoDescontoId ? Number(item.codigoMotivoDescontoId) : null,
    codigo_motivo_desconto_fidelidade_id:  item.codigoMotivoDescontoFidelidadeId ? Number(item.codigoMotivoDescontoFidelidadeId) : null,
    tipo_intermediador:                    item.tipoIntermediador ?? null,
    cnpj_do_intermediador:                 item.cnpjDoIntermediador ?? null,
    nome_do_intermediador:                 item.nomeDoIntermediador ?? null,
    indicador_de_presenca:                 item.indicadorDePresenca ?? null,
    cartao_fidelidade:                     item.cartaoFidelidade ?? null,
    loja_id:                               item.lojaId ? Number(item.lojaId) : null,
    cliente_id:                            item.clienteId ? Number(item.clienteId) : null,
    funcionario_id:                        item.funcionarioId ? Number(item.funcionarioId) : null,
    autorizador_id:                        item.autorizadorId ? Number(item.autorizadorId) : null,
    nota_fiscal_id:                        item.notaFiscalId ? Number(item.notaFiscalId) : null,
    pedido_venda_id:                       item.pedidoVendaId ? Number(item.pedidoVendaId) : null,
    tipo_preco:                            item.tipoPreco ?? null,
    transacao_venda_envelope:              item.transacaoVendaEnvelope ?? null,
  };
}

// ─── Mapper de Item do Cupom ──────────────────────────────────────────────────

export function mapCupomItemToDb(item: any, cupomExternalId: number) {
  return {
    cupom_external_id:                     cupomExternalId,
    external_item_id:                      item.id ? Number(item.id) : null,
    produto_id:                            item.produtoId ? Number(item.produtoId) : null,
    ncm:                                   item.ncm ?? null,
    csosn:                                 item.csosn ?? null,
    cfop:                                  item.cfop ?? null,
    codigo_auxiliar_id:                    item.codigoAuxiliarId ?? null,
    serie_produto:                         item.serieProduto ?? null,
    natureza:                              item.natureza ?? null,
    tipo:                                  item.tipo ?? null,
    tabela_a:                              item.tabelaA ?? null,
    tabela_b:                              item.tabelaB ?? null,
    tipo_preco:                            item.tipoPreco ?? null,
    quantidade_venda:                      d(item.quantidadeVenda),
    valor_unidade:                         d(item.valorUnidade),
    preco_venda:                           d(item.precoVenda),
    preco_custo:                           d(item.precoCusto),
    preco_custo_fiscal:                    d(item.precoCustoFiscal),
    preco_custo_medio:                     d(item.precoCustoMedio),
    valor_total:                           d(item.valorTotal),
    valor_servico:                         d(item.valorServico),
    valor_desconto:                        d(item.valorDesconto),
    tipo_de_desconto_aplicado:             item.tipoDeDescontoAplicado ?? null,
    valor_do_desconto_mega_caixa:          d(item.valorDoDescontoMegaCaixa),
    valor_acrescimo:                       d(item.valorAcrescimo),
    taxa_entrega:                          item.taxaEntrega ?? null,
    tributacao:                            item.tributacao ?? null,
    tributacao_aliquota:                   d(item.tributacaoAliquota),
    tributacao_valor_reducao:              d(item.tributacaoValorReducao),
    tributacao_aliquota_fecop:             d(item.tributacaoAliquotaFecop),
    tributacao_simbologia:                 item.tributacaoSimbologia ?? null,
    valor_fecop:                           d(item.valorFecop),
    aliquota_pis:                          d(item.aliquotaPIS),
    cst_pis:                               item.cstPIS ?? null,
    aliquota_cofins:                       d(item.aliquotaCOFINS),
    cst_cofins:                            item.cstCOFINS ?? null,
    tipo_bonificacao:                      item.tipoBonificacao ?? null,
    fator_bonificacao:                     d(item.fatorBonificacao),
    local_venda_id:                        item.localVendaId ? Number(item.localVendaId) : null,
    funcionario_vendedor_id:               item.funcionarioVendedorId ? Number(item.funcionarioVendedorId) : null,
    funcionario_autorizador_id:            item.funcionarioAutorizadorId ? Number(item.funcionarioAutorizadorId) : null,
    funcionario_captacao_prevenda_id:      item.funcionarioCaptacaoPrevendaId ?? null,
    funcionario_producao_id:               item.funcionarioProducaoId ?? null,
    setor_de_producao_id:                  item.setorDeProducaoId ? Number(item.setorDeProducaoId) : null,
    participou_promocao_desconto:          item.participouPromocaoDesconto ?? null,
    foi_vendido_em_oferta:                 item.foiVendidoEmOferta ?? null,
  };
}

// ─── Mapper de Finalização do Cupom ──────────────────────────────────────────

export function mapFinalizacaoToDb(item: any, cupomExternalId: number) {
  return {
    cupom_external_id:          cupomExternalId,
    external_finalizacao_id:    item.id ? Number(item.id) : null,
    finalizadora_id:            item.finalizadoraId ? Number(item.finalizadoraId) : null,
    sequencial:                 item.sequencial ?? null,
    tipo:                       item.tipo ?? null,
    especializacao:             item.especializacao ?? null,
    modalidade:                 item.modalidade ?? null,
    valor:                      d(item.valor) ?? '0',
    troco:                      d(item.troco),
    tipo_troco:                 item.tipoTroco ?? null,
    troco_doacao:               d(item.trocoDoacao),
    bandeira:                   item.bandeira ?? null,
    numero_cartao:              item.numeroCartao ?? null,
    numero_bin_cartao:          item.numeroBinCartao ?? null,
    nsu:                        item.nsu ?? null,
    nsu_autorizacao:            item.nsuAutorizacao ?? null,
    nsu_do_cancelamento:        item.nsuDoCancelamento ?? null,
    autorizacao_cartao:         item.autorizacaoCartao ?? null,
    rede_adquirente:            item.redeAdquirente ?? null,
    local_tef:                  item.localTef ?? null,
    quantidade_parcelas:        item.quantidadeParcelas ?? null,
    codigo_plano:               item.codigoPlano ?? null,
    plano_reducao:              item.planoReducao ?? null,
    juros_plano:                d(item.jurosPlano),
    solicita_plano:             item.solicitaPlano ?? null,
    emitente_cheque:            item.emitenteCheque ?? null,
    leitura_cmc7:               item.leituraCmc7 ?? null,
    data_vencimento:            item.dataVencimento ? new Date(item.dataVencimento) : null,
    codigo_origem:              item.codigoOrigem ?? null,
    codigo_agente:              item.codigoAgente ?? null,
    sangria_detalhada:          item.sangriaDetalhada ?? null,
    verifica_limite_credito:    item.verificaLimiteCredito ?? null,
    atualiza_limite_credito:    item.atualizaLimiteCredito ?? null,
    gera_fidelidade:            item.geraFidelidade ?? null,
    gera_conta_receber:         item.geraContaReceber ?? null,
    texto_livre1:               item.textoLivre1 ?? null,
    texto_livre2:               item.textoLivre2 ?? null,
    texto_livre3:               item.textoLivre3 ?? null,
    texto_livre4:               item.textoLivre4 ?? null,
  };
}
