// backend/src/modules/sync/mappers/nota-fiscal.mapper.ts
//
// Responsável por converter os objetos retornados pela API VarejoFácil
// nos formatos esperados pelas tabelas `nota_venda` e `nota_compra`.

/* eslint-disable @typescript-eslint/no-explicit-any */

/** Helper: converte valor para string decimal ou null */
const d = (v: unknown): string | null => (v != null ? String(v) : null);

// ─── Mapper principal da Nota Fiscal ─────────────────────────────────────────

export function mapNotaFiscalToDb(item: any, classificacao: 'VENDA' | 'COMPRA') {
  return {
    external_id:                               Number(item.id),
    numero_nota:                               String(item.numeroNota ?? ''),
    serie:                                     item.serie ?? null,
    chave_nfe:                                 item.chaveDaNfe ?? null,
    situacao:                                  item.situacao ?? 'PENDENTE',
    tipo_documento_fiscal:                     item.tipoDeDocumentoFiscal ?? null,
    tipo_de_operacao:                          item.tipoDeOperacao ?? null,
    modalidade:                                item.modalidade ?? null,
    processo_de_emissao:                       item.processoDeEmissao ?? null,
    tipo_de_geracao:                           item.tipoDeGeracao ?? null,
    classificacao,
    data_emissao:                              item.dataEmissao ? new Date(item.dataEmissao) : new Date(),
    data_operacao:                             item.dataOperacao ? new Date(item.dataOperacao) : null,
    data_exclusao:                             item.dataExclusao ? new Date(item.dataExclusao) : null,
    data_alteracao:                            item.dataAlteracao ? new Date(item.dataAlteracao) : null,
    data_posto_fiscal:                         item.dataPostoFiscal ? new Date(item.dataPostoFiscal) : null,
    valor_do_documento:                        String(item.valorDoDocumento ?? 0),
    valor_total_dos_itens:                     d(item.valorTotalDosItens),
    valor_do_desconto:                         d(item.valorDoDesconto),
    valor_de_outras_despesas:                  d(item.valorDeOutrasDespesas),
    valor_do_frete:                            d(item.valorDoFrete),
    valor_do_seguro:                           d(item.valorDoSeguro),
    valor_do_icms:                             d(item.valorDoICMS),
    valor_do_icms_substituicao_tributaria:     d(item.valorDoICMSSubstituicaoTributaria),
    valor_do_icms_desonerado:                  d(item.valorDoICMSDesonerado),
    valor_do_ipi:                              d(item.valorDoIPI),
    valor_do_pis:                              d(item.valorDoPIS),
    valor_do_cofins:                           d(item.valorDoCOFINS),
    valor_do_dae:                              d(item.valorDoDAE),
    valor_fecop:                               d(item.valorFecop),
    valor_fecop_substituicao_tributaria:       d(item.valorFecopSubstituicaoTributaria),
    base_de_calculo_do_icms:                   d(item.baseDeCalculoDoICMS),
    base_de_calculo_do_icms_substituicao_tributaria: d(item.baseDeCalculoDoICMSSubstituicaoTributaria),
    base_de_calculo_fecop:                     d(item.baseDeCalculoFecop),
    base_de_calculo_fecop_substituicao_tributaria: d(item.baseDeCalculoFecopSubstituicaoTributaria),
    loja_id:                                   item.lojaId ? Number(item.lojaId) : null,
    cliente_id:                                item.clienteId ? Number(item.clienteId) : null,
    fornecedor_id:                             item.fornecedorId ? Number(item.fornecedorId) : null,
    local_id:                                  item.localId ? Number(item.localId) : null,
    operacao_id:                               item.operacaoId ? Number(item.operacaoId) : null,
    cfop_id:                                   item.cfopId ? Number(item.cfopId) : null,
    funcionario_emissor_id:                    item.funcionarioEmissorId ? Number(item.funcionarioEmissorId) : null,
    funcionario_comprador_id:                  item.funcionarioCompradorId ? Number(item.funcionarioCompradorId) : null,
    tipo_de_frete:                             item.tipoDeFrete ?? null,
    condicao_de_pagamento:                     item.condicaoDePagamento ?? null,
    atualiza_estoque:                          item.atualizaEstoque ?? null,
    atualiza_custo:                            item.atualizaCusto ?? null,
    gera_fiscal:                               item.geraFiscal ?? null,
    compoe_abc:                                item.compoeABC ?? null,
    observacao:                                item.observacao ?? null,
  };
}

// ─── Mapper de Item da Nota Fiscal ────────────────────────────────────────────

export function mapItemNotaFiscalToDb(item: any, _notaExternalId: number) {
  return {
    external_item_id:                                   item.id ? Number(item.id) : null,
    sequencial:                                         item.sequencial ? Number(item.sequencial) : null,
    produto_id:                                         item.produtoId ? Number(item.produtoId) : null,
    ncm:                                                item.ncm ?? null,
    cest:                                               item.cest ?? null,
    cfop_id:                                            item.cfopId ? Number(item.cfopId) : null,
    unidade_de_medida:                                  item.unidadeDeMedida ?? null,
    numero_pedido:                                      item.numeroPedido ?? null,
    sequencial_item_pedido:                             item.sequencialItemPedido ?? null,
    quantidade:                                         d(item.quantidade),
    quantidade_de_itens_na_unidade:                     d(item.quantidadeDeItensNaUnidade),
    quantidade_completa:                                d(item.quantidadeCompleta),
    valor_da_embalagem:                                 d(item.valorDaEmbalagem),
    valor_total_do_item:                                d(item.valorTotalDoItem),
    valor_do_frete:                                     d(item.valorDoFrete),
    valor_do_seguro:                                    d(item.valorDoSeguro),
    valor_outras_despesas:                              d(item.valorOutrasDespesas),
    percentual_do_desconto:                             d(item.percentualDoDesconto),
    valor_do_desconto_tributado:                        d(item.valorDoDescontoTributado),
    valor_do_desconto_nao_tributado:                    d(item.valorDoDescontoNaoTributado),
    tributacao:                                         item.tributacao ?? null,
    csosn:                                              item.csosn ?? null,
    aliquota_do_icms:                                   d(item.aliquotaDoICMS),
    aliquota_no_simples:                                d(item.aliquotaNoSimples),
    aliquota_estadual:                                  d(item.aliquotaEstadual),
    aliquota_nacional:                                  d(item.aliquotaNacional),
    aliquota_importado:                                 d(item.aliquotaImportado),
    aliquota_do_icms_de_venda:                          d(item.aliquotaDoICMSDeVenda),
    base_de_calculo_do_icms:                            d(item.baseDeCalculoDoICMS),
    valor_do_icms:                                      d(item.valorDoICMS),
    valor_do_icms_no_simples:                           d(item.valorDoICMSNoSimples),
    valor_do_icms_desonerado:                           d(item.valorDoICMSDesonerado),
    valor_icms_diferimento:                             d(item.valorICMSDiferimento),
    percentual_diferimento:                             d(item.percentualDiferimento),
    motivo_desoneracao:                                 item.motivoDesoneracao ?? null,
    codigo_beneficio_fiscal:                            item.codigoBeneficioFiscal ?? null,
    aliquota_do_icms_com_substituicao_tributaria:       d(item.aliquotaDoICMSComSubstituicaoTributaria),
    aliquota_do_icms_antecipado:                        d(item.aliquotaDoICMSAntecipado),
    percentual_de_agregacao:                            d(item.percentualDeAgregacao),
    percentual_reducao_da_substituicao_tributaria:      d(item.percentualDeReducaoDASubstituicaoTributaria),
    base_de_calculo_do_icms_com_substituicao_tributaria: d(item.baseDeCalculoDoICMSComSubstituicaoTributaria),
    valor_do_icms_com_substituicao_tributaria:          d(item.valorDoICMSComSubstituicaoTributaria),
    valor_do_icms_antecipado:                           d(item.valorDoICMSAntecipado),
    percentual_tributado:                               d(item.percentualTributado),
    aliquota_do_fecop:                                  d(item.aliquotaDoFecop),
    aliquota_do_fecop_substituto:                       d(item.aliquotaDoFecopSubstituto),
    base_de_calculo_do_fecop:                           d(item.baseDeCalculoDoFecop),
    base_de_calculo_do_fecop_substituto:                d(item.baseDeCalculoDoFecopSubstituto),
    valor_do_fecop:                                     d(item.valorDoFecop),
    valor_do_fecop_substituto:                          d(item.valorDoFecopSubstituto),
    cst_do_ipi:                                         item.cstDoIPI ? Number(item.cstDoIPI) : null,
    tipo_de_entrada_ipi:                                item.tipoDeEntradaIPI ?? null,
    aliquota_do_ipi:                                    d(item.aliquotaDoIPI),
    percentual_do_ipi:                                  d(item.percentualDoIPI),
    base_de_calculo_do_ipi:                             d(item.baseDeCalculoDoIPI),
    valor_do_ipi:                                       d(item.valorDoIPI),
    cst_do_pis_id:                                      item.cstDoPISId ? Number(item.cstDoPISId) : null,
    aliquota_do_pis:                                    d(item.aliquotaDoPIS),
    base_de_calculo_do_pis:                             d(item.baseDeCalculoDoPIS),
    valor_do_pis:                                       d(item.valorDoPIS),
    cst_do_cofins_id:                                   item.cstDoCOFINSId ? Number(item.cstDoCOFINSId) : null,
    aliquota_do_cofins:                                 d(item.aliquotaDoCOFINS),
    base_de_calculo_do_cofins:                          d(item.baseDeCalculoDoCOFINS),
    valor_do_cofins:                                    d(item.valorDoCOFINS),
    percentual_do_dae:                                  d(item.percentualDoDAE),
    tipo_de_entrada_dae:                                item.tipoDeEntradaDAE ?? null,
    valor_do_dae:                                       d(item.valorDoDAE),
    custo_fiscal:                                       d(item.custoFiscal),
    custo_medio:                                        d(item.custoMedio),
    custo_reposicao:                                    d(item.custoReposicao),
    percentual_icms_de_compra:                          d(item.percentualICMSDeCompra),
    modalidade_da_base_de_calculo:                      item.modalidadeDaBaseDeCalculo ?? null,
    situacao_fiscal_id:                                 item.situacaoFiscalId ? Number(item.situacaoFiscalId) : null,
    codigo_natureza_de_imposto_federal:                 item.codigoNaturezaDeImpostoFederal ? Number(item.codigoNaturezaDeImpostoFederal) : null,
    compoe_total_da_nota:                               item.compoeTotalDaNota ?? null,
    data_validade:                                      item.dataValidade ? new Date(item.dataValidade) : null,
  };
}
