// backend/src/modules/sync/mappers/nota-fiscal.mapper.ts
/* eslint-disable @typescript-eslint/no-explicit-any */

const n = (v: unknown): number | null => (v != null ? Number(v) : null);
const d = (v: unknown): string | null =>
  v ? new Date(v as string).toISOString().slice(0, 10) : null;

export function mapNotaFiscalToDb(item: any, classificacao: 'VENDA' | 'COMPRA') {
  return {
    lojaId:                 item.lojaId                 ? Number(item.lojaId)                 : 0,
    fornecedorId:           item.fornecedorId            ? Number(item.fornecedorId)            : 0,
    clienteId:              item.clienteId               ? Number(item.clienteId)               : 0,
    operacaoId:             item.operacaoId              ? Number(item.operacaoId)              : 0,
    cfopId:                 item.cfopId                  ? Number(item.cfopId)                  : 0,
    localId:                item.localId                 ? Number(item.localId)                 : null,
    funcionarioEmissorId:   item.funcionarioEmissorId    ? Number(item.funcionarioEmissorId)    : null,
    funcionarioCompradorId: item.funcionarioCompradorId  ? Number(item.funcionarioCompradorId)  : null,
    numeroNota:             String(item.numeroNota ?? ''),
    serie:                  item.serie                   ?? null,
    chaveDaNfe:             item.chaveDaNfe              ?? null,
    situacao:               item.situacao                ?? 'PENDENTE',
    tipoDeDocumentoFiscal:  item.tipoDeDocumentoFiscal   ?? 'NF',
    tipoDeOperacao:         item.tipoDeOperacao          ?? 'SAIDA',
    condicaoDePagamento:    item.condicaoDePagamento      ?? 'A_VISTA',
    modalidade:             item.modalidade              ?? null,
    processoDeEmissao:      item.processoDeEmissao        ?? null,
    tipoDeGeracao:          item.tipoDeGeracao            ?? null,
    classificacao,
    dataEmissao:            d(item.dataEmissao)           ?? new Date().toISOString().slice(0, 10),
    dataOperacao:           d(item.dataOperacao)          ?? null,
    dataAlteracao:          d(item.dataAlteracao)         ?? null,
    dataExclusao:           d(item.dataExclusao)          ?? null,
    valorDoDocumento:       n(item.valorDoDocumento)      ?? 0,
    valorTotalDosItens:     n(item.valorTotalDosItens)    ?? n(item.valorDoDocumento) ?? 0,
    valorDoDesconto:        n(item.valorDoDesconto)       ?? null,
    valorDeOutrasDespesas:  n(item.valorDeOutrasDespesas) ?? null,
    valorDoFrete:           n(item.valorDoFrete)          ?? null,
    valorDoSeguro:          n(item.valorDoSeguro)         ?? null,
    valorDoDAE:             n(item.valorDoDAE)            ?? null,
    observacao:             item.observacao               ?? null,
    valorDoICMS:                               n(item.valorDoICMS),
    valorDoICMSSubstituicaoTributaria:         n(item.valorDoICMSSubstituicaoTributaria),
    valorDoICMSDesonerado:                     n(item.valorDoICMSDesonerado),
    valorDoIPI:                                n(item.valorDoIPI),
    valorDoPIS:                                n(item.valorDoPIS),
    valorDoCOFINS:                             n(item.valorDoCOFINS),
    valorFecop:                                n(item.valorFecop),
    valorFecopSubstituicaoTributaria:          n(item.valorFecopSubstituicaoTributaria),
    baseDeCalculoDoICMS:                       n(item.baseDeCalculoDoICMS),
    baseDeCalculoDoICMSSubstituicaoTributaria: n(item.baseDeCalculoDoICMSSubstituicaoTributaria),
    baseDeCalculoFecop:                        n(item.baseDeCalculoFecop),
    baseDeCalculoFecopSubstituicaoTributaria:  n(item.baseDeCalculoFecopSubstituicaoTributaria),
    geraFiscal:      item.geraFiscal      ?? null,
    atualizaEstoque: item.atualizaEstoque ?? null,
    atualizaCusto:   item.atualizaCusto   ?? null,
    compoeABC:       item.compoeABC       ?? null,
  };
}

export function mapItemNotaFiscalToDb(item: any) {
  return {
    produtoId:        item.produtoId        ? Number(item.produtoId)        : 0,
    situacaoFiscalId: item.situacaoFiscalId ? Number(item.situacaoFiscalId) : 0,
    cfopId:           item.cfopId           ? Number(item.cfopId)           : 0,
    cstDoPISId:       item.cstDoPISId       ? Number(item.cstDoPISId)       : null,
    cstDoCOFINSId:    item.cstDoCOFINSId    ? Number(item.cstDoCOFINSId)    : null,
    cstDoIPI:         item.cstDoIPI         ? Number(item.cstDoIPI)         : null,
    sequencial:             item.sequencial          ? Number(item.sequencial)          : null,
    ncm:                    item.ncm                 ?? null,
    cest:                   item.cest                ?? null,
    tributacao:             item.tributacao           ?? null,
    csosn:                  item.csosn               ?? null,
    unidadeDeMedida:        item.unidadeDeMedida      ?? '',
    numeroPedido:           item.numeroPedido         ?? null,
    sequencialItemPedido:   item.sequencialItemPedido ?? null,
    quantidade:                 n(item.quantidade)                  ?? 0,
    quantidadeDeItensNaUnidade: n(item.quantidadeDeItensNaUnidade)  ?? 1,
    quantidadeCompleta:         n(item.quantidadeCompleta),
    valorDaEmbalagem:            n(item.valorDaEmbalagem)            ?? 0,
    valorTotalDoItem:            n(item.valorTotalDoItem),
    valorDoDesconto:             n(item.valorDoDesconto),
    valorDoDescontoTributado:    n(item.valorDoDescontoTributado),
    valorDoDescontoNaoTributado: n(item.valorDoDescontoNaoTributado),
    valorDoFrete:                n(item.valorDoFrete),
    valorDoSeguro:               n(item.valorDoSeguro),
    valorDoDAE:                  n(item.valorDoDAE),
    valorOutrasDespesas:         n(item.valorOutrasDespesas),
    custoReposicao:              n(item.custoReposicao),
    custoMedio:                  n(item.custoMedio),
    custoFiscal:                 n(item.custoFiscal),
    percentualDoDesconto:        n(item.percentualDoDesconto),
    percentualDoFrete:           n(item.percentualDoFrete),
    percentualDoSeguro:          n(item.percentualDoSeguro),
    percentualDoDAE:             n(item.percentualDoDAE),
    percentualOutrasDespesas:    n(item.percentualOutrasDespesas),
    percentualTributado:         n(item.percentualTributado),
    percentualDiferimento:       n(item.percentualDiferimento),
    percentualICMSDeCompra:      n(item.percentualICMSDeCompra),
    percentualDeAgregacao:       n(item.percentualDeAgregacao),
    aliquotaDoICMS:              n(item.aliquotaDoICMS),
    aliquotaNoSimples:           n(item.aliquotaNoSimples),
    aliquotaEstadual:            n(item.aliquotaEstadual),
    aliquotaNacional:            n(item.aliquotaNacional),
    aliquotaImportado:           n(item.aliquotaImportado),
    baseDeCalculoDoICMS:         n(item.baseDeCalculoDoICMS),
    valorDoICMS:                 n(item.valorDoICMS),
    valorDoICMSNoSimples:        n(item.valorDoICMSNoSimples),
    valorDoICMSDesonerado:       n(item.valorDoICMSDesonerado),
    motivoDesoneracao:           item.motivoDesoneracao          ?? null,
    modalidadeDaBaseDeCalculo:   item.modalidadeDaBaseDeCalculo  ?? null,
  };
}