-- ============================================================
--  FiscalSync — Schema completo do banco de dados MySQL
--  Execute:  mysql -u root -p < fiscalsync_schema.sql
--  Ou no MySQL Workbench: File → Open SQL Script → Execute
-- ============================================================

CREATE DATABASE IF NOT EXISTS `fiscalsync`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `fiscalsync`;

-- ============================================================
-- 1. CREDENCIAL
-- ============================================================
CREATE TABLE IF NOT EXISTS `credencial` (
  `id`         INT          NOT NULL AUTO_INCREMENT,
  `api_url`    VARCHAR(500) NOT NULL COMMENT 'URL base ex: https://mercado.varejofacil.com',
  `api_key`    VARCHAR(500) NOT NULL COMMENT 'Enviada no header x-api-key',
  `created_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- 2. SYNC_CONFIG
-- ============================================================
CREATE TABLE IF NOT EXISTS `sync_config` (
  `id`             INT        NOT NULL AUTO_INCREMENT,
  `entity_type`    ENUM('nota_venda','nota_compra','cupom') NOT NULL,
  `credencial_id`  INT        NOT NULL,
  `interval_hours` ENUM('1','2','4','6','12','24') NOT NULL DEFAULT '6',
  `is_active`      TINYINT(1) NOT NULL DEFAULT 1,
  `last_sync_id`   BIGINT     NOT NULL DEFAULT 0,
  `last_sync_at`   TIMESTAMP  NULL,
  `created_at`     TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`     TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sync_config_entity_type` (`entity_type`),
  CONSTRAINT `fk_sync_config_credencial`
    FOREIGN KEY (`credencial_id`) REFERENCES `credencial` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- 3. SYNC_LOGS
-- ============================================================
CREATE TABLE IF NOT EXISTS `sync_logs` (
  `id`               INT       NOT NULL AUTO_INCREMENT,
  `entity_type`      ENUM('nota_venda','nota_compra','cupom') NOT NULL,
  `status`           ENUM('success','error','running') NOT NULL DEFAULT 'running',
  `start_id`         BIGINT    NULL,
  `end_id`           BIGINT    NULL,
  `records_imported` INT       NOT NULL DEFAULT 0,
  `error_message`    TEXT      NULL,
  `started_at`       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `finished_at`      TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_sl_entity_type` (`entity_type`),
  INDEX `idx_sl_status`      (`status`),
  INDEX `idx_sl_started_at`  (`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- 4. NOTA_VENDA — GET /v1/venda/notas-fiscais
-- ============================================================
CREATE TABLE IF NOT EXISTS `nota_venda` (
  `id`                                              INT           NOT NULL AUTO_INCREMENT,
  `external_id`                                     BIGINT        NOT NULL,
  `numero_nota`                                     VARCHAR(20)   NOT NULL,
  `serie`                                           VARCHAR(10)    NULL,
  `chave_nfe`                                       VARCHAR(44)   NULL,
  `situacao` ENUM(
    'INCONSISTENTE','RECUSADA','PRE_EFETIVADA','EFETIVADA','COM_ERRO',
    'INUTILIZADA','DENEGADA','PRE_CANCELADA','CANCELADA','PRE_ESTORNADA',
    'ESTORNADA','PENDENTE','PENDENTE_ATENDIMENTO','PENDENTE_CONFERENCIA',
    'PENDENTE_RECEPCAO','PENDENTE_INCONFORME','EXCLUIDA','PRE_INUTILIZADA',
    'CANCELADA_EXTEMPORANEO','PENDENTE_ENTREGA'
  ) NOT NULL DEFAULT 'PENDENTE',
  `tipo_documento_fiscal`                           VARCHAR(20)   NULL,
  `tipo_de_operacao`                                ENUM('ENTRADA','SAIDA') NULL,
  `modalidade`                                      VARCHAR(30)   NULL,
  `processo_de_emissao`                             VARCHAR(60)   NULL,
  `tipo_de_geracao`                                 VARCHAR(60)   NULL,
  `classificacao`                                   ENUM('COMPRA','VENDA') NULL DEFAULT 'VENDA',
  `data_emissao`                                    DATE          NOT NULL,
  `data_operacao`                                   DATE          NULL,
  `data_exclusao`                                   DATE          NULL,
  `data_alteracao`                                  DATE          NULL,
  `data_posto_fiscal`                               DATE          NULL,
  `valor_do_documento`                              DECIMAL(15,4) NOT NULL,
  `valor_total_dos_itens`                           DECIMAL(15,4) NULL,
  `valor_do_desconto`                               DECIMAL(15,4) NULL,
  `valor_de_outras_despesas`                        DECIMAL(15,4) NULL,
  `valor_do_frete`                                  DECIMAL(15,4) NULL,
  `valor_do_seguro`                                 DECIMAL(15,4) NULL,
  `valor_do_icms`                                   DECIMAL(15,4) NULL,
  `valor_do_icms_substituicao_tributaria`           DECIMAL(15,4) NULL,
  `valor_do_icms_desonerado`                        DECIMAL(15,4) NULL,
  `valor_do_ipi`                                    DECIMAL(15,4) NULL,
  `valor_do_pis`                                    DECIMAL(15,4) NULL,
  `valor_do_cofins`                                 DECIMAL(15,4) NULL,
  `valor_do_dae`                                    DECIMAL(15,4) NULL,
  `valor_fecop`                                     DECIMAL(15,4) NULL,
  `valor_fecop_substituicao_tributaria`             DECIMAL(15,4) NULL,
  `base_de_calculo_do_icms`                         DECIMAL(15,4) NULL,
  `base_de_calculo_do_icms_substituicao_tributaria` DECIMAL(15,4) NULL,
  `base_de_calculo_fecop`                           DECIMAL(15,4) NULL,
  `base_de_calculo_fecop_substituicao_tributaria`   DECIMAL(15,4) NULL,
  `loja_id`                                         BIGINT        NULL,
  `cliente_id`                                      BIGINT        NULL,
  `fornecedor_id`                                   BIGINT        NULL,
  `local_id`                                        BIGINT        NULL,
  `operacao_id`                                     BIGINT        NULL,
  `cfop_id`                                         BIGINT        NULL,
  `funcionario_emissor_id`                          BIGINT        NULL,
  `funcionario_comprador_id`                        BIGINT        NULL,
  `tipo_de_frete`                                   VARCHAR(30)   NULL,
  `condicao_de_pagamento`                           VARCHAR(20)   NULL,
  `atualiza_estoque`                                TINYINT(1)    NULL,
  `atualiza_custo`                                  TINYINT(1)    NULL,
  `gera_fiscal`                                     TINYINT(1)    NULL,
  `compoe_abc`                                      TINYINT(1)    NULL,
  `observacao`                                      TEXT          NULL,
  `created_at`                                      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                                      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_nv_external_id` (`external_id`),
  UNIQUE KEY `uq_nv_chave_nfe`   (`chave_nfe`),
  INDEX `idx_nv_data_emissao`    (`data_emissao`),
  INDEX `idx_nv_situacao`        (`situacao`),
  INDEX `idx_nv_loja_id`         (`loja_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- 5. NOTA_VENDA_ITEM
-- ============================================================
CREATE TABLE IF NOT EXISTS `nota_venda_item` (
  `id`                                                    INT           NOT NULL AUTO_INCREMENT,
  `nota_venda_external_id`                                BIGINT        NOT NULL,
  `external_item_id`                                      BIGINT        NULL,
  `sequencial`                                            BIGINT        NULL,
  `produto_id`                                            BIGINT        NULL,
  `ncm`                                                   VARCHAR(8)    NULL,
  `cest`                                                  VARCHAR(8)    NULL,
  `cfop_id`                                               BIGINT        NULL,
  `unidade_de_medida`                                     VARCHAR(3)    NULL,
  `numero_pedido`                                         VARCHAR(50)   NULL,
  `sequencial_item_pedido`                                VARCHAR(20)   NULL,
  `quantidade`                                            DECIMAL(15,4) NULL,
  `quantidade_de_itens_na_unidade`                        DECIMAL(15,4) NULL,
  `quantidade_completa`                                   DECIMAL(15,4) NULL,
  `valor_da_embalagem`                                    DECIMAL(15,4) NULL,
  `valor_total_do_item`                                   DECIMAL(15,4) NULL,
  `valor_do_frete`                                        DECIMAL(15,4) NULL,
  `valor_do_seguro`                                       DECIMAL(15,4) NULL,
  `valor_outras_despesas`                                 DECIMAL(15,4) NULL,
  `percentual_do_desconto`                                DECIMAL(10,4) NULL,
  `valor_do_desconto_tributado`                           DECIMAL(15,4) NULL,
  `valor_do_desconto_nao_tributado`                       DECIMAL(15,4) NULL,
  `tributacao`                                            VARCHAR(3)    NULL,
  `csosn`                                                 VARCHAR(80)   NULL,
  `aliquota_do_icms`                                      DECIMAL(10,4) NULL,
  `aliquota_no_simples`                                   DECIMAL(10,4) NULL,
  `aliquota_estadual`                                     DECIMAL(10,4) NULL,
  `aliquota_nacional`                                     DECIMAL(10,4) NULL,
  `aliquota_importado`                                    DECIMAL(10,4) NULL,
  `aliquota_do_icms_de_venda`                             DECIMAL(10,4) NULL,
  `base_de_calculo_do_icms`                               DECIMAL(15,4) NULL,
  `valor_do_icms`                                         DECIMAL(15,4) NULL,
  `valor_do_icms_no_simples`                              DECIMAL(15,4) NULL,
  `valor_do_icms_desonerado`                              DECIMAL(15,4) NULL,
  `valor_icms_diferimento`                                DECIMAL(15,4) NULL,
  `percentual_diferimento`                                DECIMAL(10,4) NULL,
  `motivo_desoneracao`                                    VARCHAR(50)   NULL,
  `codigo_beneficio_fiscal`                               VARCHAR(20)   NULL,
  `aliquota_do_icms_com_substituicao_tributaria`          DECIMAL(10,4) NULL,
  `aliquota_do_icms_antecipado`                           DECIMAL(10,4) NULL,
  `percentual_de_agregacao`                               DECIMAL(10,4) NULL,
  `percentual_reducao_da_substituicao_tributaria`         DECIMAL(10,4) NULL,
  `base_de_calculo_do_icms_com_substituicao_tributaria`   DECIMAL(15,4) NULL,
  `valor_do_icms_com_substituicao_tributaria`             DECIMAL(15,4) NULL,
  `valor_do_icms_antecipado`                              DECIMAL(15,4) NULL,
  `percentual_tributado`                                  DECIMAL(10,4) NULL,
  `aliquota_do_fecop`                                     DECIMAL(10,4) NULL,
  `aliquota_do_fecop_substituto`                          DECIMAL(10,4) NULL,
  `base_de_calculo_do_fecop`                              DECIMAL(15,4) NULL,
  `base_de_calculo_do_fecop_substituto`                   DECIMAL(15,4) NULL,
  `valor_do_fecop`                                        DECIMAL(15,4) NULL,
  `valor_do_fecop_substituto`                             DECIMAL(15,4) NULL,
  `cst_do_ipi`                                            BIGINT        NULL,
  `tipo_de_entrada_ipi`                                   VARCHAR(10)   NULL,
  `aliquota_do_ipi`                                       DECIMAL(10,4) NULL,
  `percentual_do_ipi`                                     DECIMAL(10,4) NULL,
  `base_de_calculo_do_ipi`                                DECIMAL(15,4) NULL,
  `valor_do_ipi`                                          DECIMAL(15,4) NULL,
  `cst_do_pis_id`                                         BIGINT        NULL,
  `aliquota_do_pis`                                       DECIMAL(10,4) NULL,
  `base_de_calculo_do_pis`                                DECIMAL(15,4) NULL,
  `valor_do_pis`                                          DECIMAL(15,4) NULL,
  `cst_do_cofins_id`                                      BIGINT        NULL,
  `aliquota_do_cofins`                                    DECIMAL(10,4) NULL,
  `base_de_calculo_do_cofins`                             DECIMAL(15,4) NULL,
  `valor_do_cofins`                                       DECIMAL(15,4) NULL,
  `percentual_do_dae`                                     DECIMAL(10,4) NULL,
  `tipo_de_entrada_dae`                                   VARCHAR(10)   NULL,
  `valor_do_dae`                                          DECIMAL(15,4) NULL,
  `custo_fiscal`                                          DECIMAL(15,4) NULL,
  `custo_medio`                                           DECIMAL(15,4) NULL,
  `custo_reposicao`                                       DECIMAL(15,4) NULL,
  `percentual_icms_de_compra`                             DECIMAL(10,4) NULL,
  `modalidade_da_base_de_calculo`                         VARCHAR(30)   NULL,
  `situacao_fiscal_id`                                    BIGINT        NULL,
  `codigo_natureza_de_imposto_federal`                    BIGINT        NULL,
  `compoe_total_da_nota`                                  TINYINT(1)    NULL,
  `data_validade`                                         DATE          NULL,
  `created_at`                                            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                                            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_nvi_nota_venda_external_id` (`nota_venda_external_id`),
  INDEX `idx_nvi_produto_id`             (`produto_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- 6. NOTA_COMPRA — GET /v1/compra/notas-fiscais
-- ============================================================
CREATE TABLE IF NOT EXISTS `nota_compra` (
  `id`                                              INT           NOT NULL AUTO_INCREMENT,
  `external_id`                                     BIGINT        NOT NULL,
  `numero_nota`                                     VARCHAR(20)   NOT NULL,
  `serie`                                           VARCHAR(10)    NULL,
  `chave_nfe`                                       VARCHAR(44)   NULL,
  `situacao` ENUM(
    'INCONSISTENTE','RECUSADA','PRE_EFETIVADA','EFETIVADA','COM_ERRO',
    'INUTILIZADA','DENEGADA','PRE_CANCELADA','CANCELADA','PRE_ESTORNADA',
    'ESTORNADA','PENDENTE','PENDENTE_ATENDIMENTO','PENDENTE_CONFERENCIA',
    'PENDENTE_RECEPCAO','PENDENTE_INCONFORME','EXCLUIDA','PRE_INUTILIZADA',
    'CANCELADA_EXTEMPORANEO','PENDENTE_ENTREGA'
  ) NOT NULL DEFAULT 'PENDENTE',
  `tipo_documento_fiscal`                           VARCHAR(20)   NULL,
  `tipo_de_operacao`                                ENUM('ENTRADA','SAIDA') NULL,
  `modalidade`                                      VARCHAR(30)   NULL,
  `processo_de_emissao`                             VARCHAR(60)   NULL,
  `tipo_de_geracao`                                 VARCHAR(60)   NULL,
  `classificacao`                                   ENUM('COMPRA','VENDA') NULL DEFAULT 'COMPRA',
  `data_emissao`                                    DATE          NOT NULL,
  `data_operacao`                                   DATE          NULL,
  `data_exclusao`                                   DATE          NULL,
  `data_alteracao`                                  DATE          NULL,
  `data_posto_fiscal`                               DATE          NULL,
  `valor_do_documento`                              DECIMAL(15,4) NOT NULL,
  `valor_total_dos_itens`                           DECIMAL(15,4) NULL,
  `valor_do_desconto`                               DECIMAL(15,4) NULL,
  `valor_de_outras_despesas`                        DECIMAL(15,4) NULL,
  `valor_do_frete`                                  DECIMAL(15,4) NULL,
  `valor_do_seguro`                                 DECIMAL(15,4) NULL,
  `valor_do_icms`                                   DECIMAL(15,4) NULL,
  `valor_do_icms_substituicao_tributaria`           DECIMAL(15,4) NULL,
  `valor_do_icms_desonerado`                        DECIMAL(15,4) NULL,
  `valor_do_ipi`                                    DECIMAL(15,4) NULL,
  `valor_do_pis`                                    DECIMAL(15,4) NULL,
  `valor_do_cofins`                                 DECIMAL(15,4) NULL,
  `valor_do_dae`                                    DECIMAL(15,4) NULL,
  `valor_fecop`                                     DECIMAL(15,4) NULL,
  `valor_fecop_substituicao_tributaria`             DECIMAL(15,4) NULL,
  `base_de_calculo_do_icms`                         DECIMAL(15,4) NULL,
  `base_de_calculo_do_icms_substituicao_tributaria` DECIMAL(15,4) NULL,
  `base_de_calculo_fecop`                           DECIMAL(15,4) NULL,
  `base_de_calculo_fecop_substituicao_tributaria`   DECIMAL(15,4) NULL,
  `loja_id`                                         BIGINT        NULL,
  `cliente_id`                                      BIGINT        NULL,
  `fornecedor_id`                                   BIGINT        NULL,
  `local_id`                                        BIGINT        NULL,
  `operacao_id`                                     BIGINT        NULL,
  `cfop_id`                                         BIGINT        NULL,
  `funcionario_emissor_id`                          BIGINT        NULL,
  `funcionario_comprador_id`                        BIGINT        NULL,
  `tipo_de_frete`                                   VARCHAR(30)   NULL,
  `condicao_de_pagamento`                           VARCHAR(20)   NULL,
  `atualiza_estoque`                                TINYINT(1)    NULL,
  `atualiza_custo`                                  TINYINT(1)    NULL,
  `gera_fiscal`                                     TINYINT(1)    NULL,
  `compoe_abc`                                      TINYINT(1)    NULL,
  `observacao`                                      TEXT          NULL,
  `created_at`                                      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                                      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_nc_external_id` (`external_id`),
  UNIQUE KEY `uq_nc_chave_nfe`   (`chave_nfe`),
  INDEX `idx_nc_data_emissao`    (`data_emissao`),
  INDEX `idx_nc_situacao`        (`situacao`),
  INDEX `idx_nc_loja_id`         (`loja_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- 7. NOTA_COMPRA_ITEM
-- ============================================================
CREATE TABLE IF NOT EXISTS `nota_compra_item` (
  `id`                                                    INT           NOT NULL AUTO_INCREMENT,
  `nota_compra_external_id`                               BIGINT        NOT NULL,
  `external_item_id`                                      BIGINT        NULL,
  `sequencial`                                            BIGINT        NULL,
  `produto_id`                                            BIGINT        NULL,
  `ncm`                                                   VARCHAR(8)    NULL,
  `cest`                                                  VARCHAR(8)    NULL,
  `cfop_id`                                               BIGINT        NULL,
  `unidade_de_medida`                                     VARCHAR(3)    NULL,
  `numero_pedido`                                         VARCHAR(50)   NULL,
  `sequencial_item_pedido`                                VARCHAR(20)   NULL,
  `quantidade`                                            DECIMAL(15,4) NULL,
  `quantidade_de_itens_na_unidade`                        DECIMAL(15,4) NULL,
  `quantidade_completa`                                   DECIMAL(15,4) NULL,
  `valor_da_embalagem`                                    DECIMAL(15,4) NULL,
  `valor_total_do_item`                                   DECIMAL(15,4) NULL,
  `valor_do_frete`                                        DECIMAL(15,4) NULL,
  `valor_do_seguro`                                       DECIMAL(15,4) NULL,
  `valor_outras_despesas`                                 DECIMAL(15,4) NULL,
  `percentual_do_desconto`                                DECIMAL(10,4) NULL,
  `valor_do_desconto_tributado`                           DECIMAL(15,4) NULL,
  `valor_do_desconto_nao_tributado`                       DECIMAL(15,4) NULL,
  `tributacao`                                            VARCHAR(3)    NULL,
  `csosn`                                                 VARCHAR(80)   NULL,
  `aliquota_do_icms`                                      DECIMAL(10,4) NULL,
  `aliquota_no_simples`                                   DECIMAL(10,4) NULL,
  `aliquota_estadual`                                     DECIMAL(10,4) NULL,
  `aliquota_nacional`                                     DECIMAL(10,4) NULL,
  `aliquota_importado`                                    DECIMAL(10,4) NULL,
  `aliquota_do_icms_de_venda`                             DECIMAL(10,4) NULL,
  `base_de_calculo_do_icms`                               DECIMAL(15,4) NULL,
  `valor_do_icms`                                         DECIMAL(15,4) NULL,
  `valor_do_icms_no_simples`                              DECIMAL(15,4) NULL,
  `valor_do_icms_desonerado`                              DECIMAL(15,4) NULL,
  `valor_icms_diferimento`                                DECIMAL(15,4) NULL,
  `percentual_diferimento`                                DECIMAL(10,4) NULL,
  `motivo_desoneracao`                                    VARCHAR(50)   NULL,
  `codigo_beneficio_fiscal`                               VARCHAR(20)   NULL,
  `aliquota_do_icms_com_substituicao_tributaria`          DECIMAL(10,4) NULL,
  `aliquota_do_icms_antecipado`                           DECIMAL(10,4) NULL,
  `percentual_de_agregacao`                               DECIMAL(10,4) NULL,
  `percentual_reducao_da_substituicao_tributaria`         DECIMAL(10,4) NULL,
  `base_de_calculo_do_icms_com_substituicao_tributaria`   DECIMAL(15,4) NULL,
  `valor_do_icms_com_substituicao_tributaria`             DECIMAL(15,4) NULL,
  `valor_do_icms_antecipado`                              DECIMAL(15,4) NULL,
  `percentual_tributado`                                  DECIMAL(10,4) NULL,
  `aliquota_do_fecop`                                     DECIMAL(10,4) NULL,
  `aliquota_do_fecop_substituto`                          DECIMAL(10,4) NULL,
  `base_de_calculo_do_fecop`                              DECIMAL(15,4) NULL,
  `base_de_calculo_do_fecop_substituto`                   DECIMAL(15,4) NULL,
  `valor_do_fecop`                                        DECIMAL(15,4) NULL,
  `valor_do_fecop_substituto`                             DECIMAL(15,4) NULL,
  `cst_do_ipi`                                            BIGINT        NULL,
  `tipo_de_entrada_ipi`                                   VARCHAR(10)   NULL,
  `aliquota_do_ipi`                                       DECIMAL(10,4) NULL,
  `percentual_do_ipi`                                     DECIMAL(10,4) NULL,
  `base_de_calculo_do_ipi`                                DECIMAL(15,4) NULL,
  `valor_do_ipi`                                          DECIMAL(15,4) NULL,
  `cst_do_pis_id`                                         BIGINT        NULL,
  `aliquota_do_pis`                                       DECIMAL(10,4) NULL,
  `base_de_calculo_do_pis`                                DECIMAL(15,4) NULL,
  `valor_do_pis`                                          DECIMAL(15,4) NULL,
  `cst_do_cofins_id`                                      BIGINT        NULL,
  `aliquota_do_cofins`                                    DECIMAL(10,4) NULL,
  `base_de_calculo_do_cofins`                             DECIMAL(15,4) NULL,
  `valor_do_cofins`                                       DECIMAL(15,4) NULL,
  `percentual_do_dae`                                     DECIMAL(10,4) NULL,
  `tipo_de_entrada_dae`                                   VARCHAR(10)   NULL,
  `valor_do_dae`                                          DECIMAL(15,4) NULL,
  `custo_fiscal`                                          DECIMAL(15,4) NULL,
  `custo_medio`                                           DECIMAL(15,4) NULL,
  `custo_reposicao`                                       DECIMAL(15,4) NULL,
  `percentual_icms_de_compra`                             DECIMAL(10,4) NULL,
  `modalidade_da_base_de_calculo`                         VARCHAR(30)   NULL,
  `situacao_fiscal_id`                                    BIGINT        NULL,
  `codigo_natureza_de_imposto_federal`                    BIGINT        NULL,
  `compoe_total_da_nota`                                  TINYINT(1)    NULL,
  `data_validade`                                         DATE          NULL,
  `created_at`                                            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                                            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_nci_nota_compra_external_id` (`nota_compra_external_id`),
  INDEX `idx_nci_produto_id`              (`produto_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- 8. CUPOM — GET /v1/venda/cupons-fiscais
-- ============================================================
CREATE TABLE IF NOT EXISTS `cupom` (
  `id`                                   BIGINT        NOT NULL AUTO_INCREMENT,
  `external_id`                          BIGINT        NOT NULL COMMENT 'identificadorId da API',
  `id_externo`                           VARCHAR(36)   NULL,
  `coo`                                  INT           NULL,
  `sequencial`                           VARCHAR(20)   NULL,
  `numero_caixa`                         VARCHAR(3)    NULL,
  `numero_equipamento`                   VARCHAR(50)   NULL,
  `serie_equipamento`                    VARCHAR(50)   NULL,
  `sequencial_operador`                  VARCHAR(20)   NULL,
  `codigo_impressora`                    VARCHAR(20)   NULL,
  `contador_documento`                   VARCHAR(20)   NULL,
  `chave_eletronica`                     VARCHAR(50)   NULL,
  `numero_do_protocolo`                  VARCHAR(50)   NULL,
  `status_xml_nota` ENUM('PENDENTE','AUTORIZADA','PENDENTE_CANCELAMENTO','CANCELADA','ERRO','REJEITADA') NULL,
  `data`                                 DATE          NOT NULL,
  `data_venda`                           DATE          NULL,
  `hora`                                 VARCHAR(8)    NULL,
  `data_hora_abertura_cupom`             VARCHAR(30)   NULL,
  `data_hora_fechamento_cupom`           VARCHAR(30)   NULL,
  `criado_em`                            DATE          NULL,
  `nome_consumidor`                      VARCHAR(200)  NULL,
  `cpf_consumidor`                       VARCHAR(14)   NULL,
  `valor`                                DECIMAL(15,4) NOT NULL,
  `acrescimo`                            DECIMAL(15,4) NULL,
  `desconto`                             DECIMAL(15,4) NULL,
  `valor_desconto_fidelidade`            DECIMAL(15,4) NULL,
  `valor_servico`                        DECIMAL(15,4) NULL,
  `valor_itens_cancelados`               DECIMAL(15,4) NULL,
  `margem_desconto`                      DECIMAL(10,4) NULL,
  `qtd_itens_cupom`                      DECIMAL(10,4) NULL,
  `qtd_itens_cancelados`                 DECIMAL(10,4) NULL,
  `qtd_unidades_cupom`                   DECIMAL(10,4) NULL,
  `qtd_unidades_canceladas`              DECIMAL(10,4) NULL,
  `cancelada`                            TINYINT(1)    NULL,
  `imprimiu_nota_fiscal`                 TINYINT(1)    NULL,
  `tem_itens_vendido_em_oferta`          TINYINT(1)    NULL,
  `abono_servico`                        TINYINT(1)    NULL,
  `justificativa_cancelamento`           TEXT          NULL,
  `sequencial_cupom_cancelado`           VARCHAR(20)   NULL,
  `codigo_motivo_cancelamento_id`        BIGINT        NULL,
  `justificativa_desconto`               TEXT          NULL,
  `codigo_motivo_desconto_id`            BIGINT        NULL,
  `codigo_motivo_desconto_fidelidade_id` BIGINT        NULL,
  `tipo_intermediador`                   VARCHAR(20)   NULL,
  `cnpj_do_intermediador`                VARCHAR(20)   NULL,
  `nome_do_intermediador`                VARCHAR(200)  NULL,
  `indicador_de_presenca`                VARCHAR(10)   NULL,
  `cartao_fidelidade`                    VARCHAR(50)   NULL,
  `loja_id`                              BIGINT        NULL,
  `cliente_id`                           BIGINT        NULL,
  `funcionario_id`                       INT           NULL,
  `autorizador_id`                       INT           NULL,
  `nota_fiscal_id`                       BIGINT        NULL,
  `pedido_venda_id`                      BIGINT        NULL,
  `tipo_preco`                           VARCHAR(20)   NULL,
  `transacao_venda_envelope`             TEXT          NULL,
  `created_at`                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cupom_external_id` (`external_id`),
  UNIQUE KEY `uq_cupom_chave`       (`chave_eletronica`),
  INDEX `idx_cupom_data`            (`data`),
  INDEX `idx_cupom_loja_id`         (`loja_id`),
  INDEX `idx_cupom_cancelada`       (`cancelada`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- 9. CUPOM_ITEM — itensVenda dos cupons
-- ============================================================
CREATE TABLE IF NOT EXISTS `cupom_item` (
  `id`                                INT           NOT NULL AUTO_INCREMENT,
  `cupom_external_id`                 BIGINT        NOT NULL,
  `external_item_id`                  INT           NULL,
  `produto_id`                        BIGINT        NULL,
  `ncm`                               VARCHAR(8)    NULL,
  `csosn`                             VARCHAR(10)   NULL,
  `cfop`                              VARCHAR(10)   NULL,
  `codigo_auxiliar_id`                VARCHAR(50)   NULL,
  `serie_produto`                     VARCHAR(20)   NULL,
  `natureza`                          VARCHAR(10)   NULL,
  `tipo`                              VARCHAR(5)    NULL COMMENT '1=Vendido 2=Cancelado',
  `tabela_a`                          VARCHAR(10)   NULL,
  `tabela_b`                          VARCHAR(10)   NULL,
  `tipo_preco`                        VARCHAR(20)   NULL,
  `quantidade_venda`                  DECIMAL(15,4) NULL,
  `valor_unidade`                     DECIMAL(15,4) NULL,
  `preco_venda`                       DECIMAL(15,4) NULL,
  `preco_custo`                       DECIMAL(15,4) NULL,
  `preco_custo_fiscal`                DECIMAL(15,4) NULL,
  `preco_custo_medio`                 DECIMAL(15,4) NULL,
  `valor_total`                       DECIMAL(15,4) NULL,
  `valor_servico`                     DECIMAL(15,4) NULL,
  `valor_desconto`                    DECIMAL(15,4) NULL,
  `tipo_de_desconto_aplicado`         VARCHAR(20)   NULL,
  `valor_do_desconto_mega_caixa`      DECIMAL(15,4) NULL,
  `valor_acrescimo`                   DECIMAL(15,4) NULL,
  `taxa_entrega`                      TINYINT(1)    NULL,
  `tributacao`                        VARCHAR(10)   NULL,
  `tributacao_aliquota`               DECIMAL(10,4) NULL,
  `tributacao_valor_reducao`          DECIMAL(15,4) NULL,
  `tributacao_aliquota_fecop`         DECIMAL(10,4) NULL,
  `tributacao_simbologia`             VARCHAR(10)   NULL,
  `valor_fecop`                       DECIMAL(15,4) NULL,
  `aliquota_pis`                      DECIMAL(10,4) NULL,
  `cst_pis`                           VARCHAR(5)    NULL,
  `aliquota_cofins`                   DECIMAL(10,4) NULL,
  `cst_cofins`                        VARCHAR(5)    NULL,
  `tipo_bonificacao`                  VARCHAR(20)   NULL,
  `fator_bonificacao`                 DECIMAL(10,4) NULL,
  `local_venda_id`                    BIGINT        NULL,
  `funcionario_vendedor_id`           INT           NULL,
  `funcionario_autorizador_id`        INT           NULL,
  `funcionario_captacao_prevenda_id`  VARCHAR(50)   NULL,
  `funcionario_producao_id`           VARCHAR(50)   NULL,
  `setor_de_producao_id`              INT           NULL,
  `participou_promocao_desconto`      TINYINT(1)    NULL,
  `foi_vendido_em_oferta`             TINYINT(1)    NULL,
  `created_at`                        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_ci_cupom_external_id` (`cupom_external_id`),
  INDEX `idx_ci_produto_id`        (`produto_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- 10. CUPOM_FINALIZACAO — finalizacoes dos cupons (pagamentos)
-- ============================================================
CREATE TABLE IF NOT EXISTS `cupom_finalizacao` (
  `id`                        INT           NOT NULL AUTO_INCREMENT,
  `cupom_external_id`         BIGINT        NOT NULL,
  `external_finalizacao_id`   INT           NULL,
  `finalizadora_id`           INT           NULL,
  `sequencial`                VARCHAR(3)    NULL,
  `tipo`                      VARCHAR(30)   NULL COMMENT 'DINHEIRO, CARTAO, CHEQUE, PIX...',
  `especializacao`            VARCHAR(50)   NULL,
  `modalidade`                VARCHAR(50)   NULL,
  `valor`                     DECIMAL(15,4) NOT NULL,
  `troco`                     DECIMAL(15,4) NULL,
  `tipo_troco`                VARCHAR(1)    NULL,
  `troco_doacao`              DECIMAL(15,4) NULL,
  `bandeira`                  VARCHAR(50)   NULL,
  `numero_cartao`             VARCHAR(30)   NULL,
  `numero_bin_cartao`         VARCHAR(10)   NULL,
  `nsu`                       VARCHAR(30)   NULL,
  `nsu_autorizacao`           VARCHAR(30)   NULL,
  `nsu_do_cancelamento`       VARCHAR(30)   NULL,
  `autorizacao_cartao`        VARCHAR(30)   NULL,
  `rede_adquirente`           VARCHAR(50)   NULL,
  `local_tef`                 VARCHAR(10)   NULL COMMENT 'POS, TEF, DISCADA',
  `quantidade_parcelas`       VARCHAR(5)    NULL,
  `codigo_plano`              VARCHAR(20)   NULL,
  `plano_reducao`             VARCHAR(20)   NULL,
  `juros_plano`               DECIMAL(10,4) NULL,
  `solicita_plano`            VARCHAR(1)    NULL,
  `emitente_cheque`           VARCHAR(100)  NULL,
  `leitura_cmc7`              VARCHAR(50)   NULL,
  `data_vencimento`           DATE          NULL,
  `numero_vale_compra`        VARCHAR(50)   NULL,
  `desconto_moeda`            DECIMAL(15,4) NULL,
  `codigo_origem`             VARCHAR(20)   NULL,
  `codigo_agente`             VARCHAR(20)   NULL,
  `sangria_detalhada`         VARCHAR(50)   NULL,
  `verifica_limite_credito`   VARCHAR(1)    NULL,
  `atualiza_limite_credito`   VARCHAR(1)    NULL,
  `gera_fidelidade`           VARCHAR(1)    NULL,
  `gera_conta_receber`        VARCHAR(1)    NULL,
  `texto_livre1`              VARCHAR(200)  NULL,
  `texto_livre2`              VARCHAR(200)  NULL,
  `texto_livre3`              VARCHAR(200)  NULL,
  `texto_livre4`              VARCHAR(200)  NULL,
  `created_at`                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_cf_cupom_external_id` (`cupom_external_id`),
  INDEX `idx_cf_finalizadora_id`   (`finalizadora_id`),
  INDEX `idx_cf_tipo`              (`tipo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- VERIFICAÇÃO: lista as tabelas criadas
-- ============================================================
SELECT TABLE_NAME AS `Tabela criada`
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = 'fiscalsync'
ORDER BY TABLE_NAME;
